dat=input('Fecha: ')
nom=input('Nombre: ')
ape=input('Apellido: ')
pas=input('Pasaporte: ')
sdat=20-len(dat)
snom=19-len(nom)
sape=17-len(ape)
spas=16-len(pas)
print('.'*30)
print('.'+' '*10+' Boleta '+' '*10+'.')
print('.'*30)
print('.'+' Fecha: '+ dat+' '*sdat+'.')
print('.'+' Nombre: '+ nom+' '*snom+'.')
print('.'+' Apellido: '+ ape+' '*sape+'.')
print('.'+' Pasaporte: '+ pas+' '*spas+'.')
print('.'*30)
